### ISSUE TITLE
25k signatures

### ISSUE THREAD

**Issue by phiweger** [dib-lab/sourmash_databases#4]
hi @ctb,

I think the "real" GTDB has about 150k genomes, and 25k genomes sounds like a dereplicated set used by the GTDB toolkit, or am I missing something here? Maybe the 25k genomes correspond to [this subset by the same group around Donovan Parks](https://www.biorxiv.org/content/10.1101/771964v2)?

kind regards,
Adrian

**Comment by ctb** [comment]
yep, Donovan pointed that out to me this morning! Working on it.

The 25k dereplicated seem like a good ~small set to use, tho. More tomorrow.

**Comment by phiweger** [comment]
I think a small index would be a great idea, bc/ the GTDB "raw" contains about 10% E. coli :)

Just for completeness, we recently dereplicated the GTDB non-manually (compared w/ Parks et al.) see [here](https://www.biorxiv.org/content/10.1101/855262v2.full) -- classification accuracy was near-identical.

**Comment by ctb** [comment]
closing in favor of https://github.com/sourmash-bio/sourmash/issues/2015 and, well, many other things, but https://github.com/sourmash-bio/sourmash/issues/1941 too.
