### ISSUE TITLE
check genome_updater for genbank/refseq downloads

### ISSUE THREAD

**Issue by luizirber** [dib-lab/sourmash_databases#5]
I used https://github.com/kblin/ncbi-genome-download to download data before, but it is a bit hard to update after the first download. `genome_updater` seems to be geared towards this use case: https://github.com/pirovc/genome_updater

**Comment by luizirber** [comment]
I used it to create a mirrored subset of genbank and refseq (archaea, bacteria, fungi, viral, protozoa), and [really liked it](https://twitter.com/luizirber/status/1256651327196676096). I don't have time to make a pull request now, but some blueprints:

- `genome_updater.sh` supports recovering files from a [previously obtained assembly summary][0] file with the `-e` option. This is really useful for reproducing how a database was built, and we can stored it somewhere (osf? zenodo?)
- Instead of finding all files in a dir, use the `assembly_summary.txt` to select files (from a domain like 'archaea' or 'fungi').
- From previous item: build separate DBs for each domain. This is something that the euk SBTs already do (see https://github.com/dib-lab/2018-euk-SBTs and https://osf.io/a46zr/)
- Another benefit of using the `assembly_summary.txt`: We don't depend on `acc2taxid` to get the taxonomy of each dataset. This can also be a mapping generated during database construction, and saved in the zipped SBT (or whatever taxonomy format we end up adopting in sourmash: https://github.com/dib-lab/sourmash/issues/969

I think most of these items fit https://github.com/dib-lab/sourmash/issues/970 too.

[0]: https://github.com/pirovc/genome_updater#recovering-fasta-files-from-a-previously-obtained-assembly_summarytxt

**Comment by ctb** [comment]
cool, I'll look into using it - is there a seed on farm that I can start from, or shall I just re-download the whole shebang?

**Comment by luizirber** [comment]
Re-download, I did this in my machine.

**Comment by ctb** [comment]
Very good experience so far --

```
# make group directory
cd /group/ctbrowngrp
mkdir ncbi-genomes
cd ncbi-genomes

# install genome_updater
13820  conda create -n genupd -y genome_updater 
13821  conda activate genupd

# grab all shewanella genomes - dry run
genome_updater.sh -g "taxids:22" -k -m -o shew

# with one thread
genome_updater.sh -g "taxids:22" -m -o shew

# with four threads, + fix directory (-i)
genome_updater.sh -g "taxids:22" -m -o shew -i -t 4
```

**Comment by luizirber** [comment]
> Another benefit of using the `assembly_summary.txt`: We don't depend on `acc2taxid` to get the taxonomy of each dataset. This can also be a mapping generated during database construction, and saved in the zipped SBT (or whatever taxonomy format we end up adopting in sourmash: [dib-lab/sourmash#969](https://github.com/dib-lab/sourmash/issues/969)

Also: instead of using `--name-from-first`, set the `--name` based on the `assembly_summary.txt`. This gives us better control on the right accession number, or even using the `GCF`/`GCA` identifiers instead. More info: https://github.com/luizirber/2020-cami/issues/1

**Comment by ctb** [comment]
(yep, that's how the GTDB snakemake does it)

**Comment by ctb** [comment]
note to self, put things in `/group/ctbrowngrp/`

**Comment by ctb** [comment]
closing in favor of our modern database build practices.
